/**
 * IFC Streaming Reader - parses existing IFC files line-by-line
 * Handles GB-size files without loading everything into memory.
 *
 * Instead of web-ifc (which loads the entire file into WASM memory and crashes
 * on 2+ GB files), this reads the STEP format text directly.
 *
 * Supported IFC entities (generated by Paula or similar tools):
 * - IFCCARTESIANPOINTLIST3D → vertex coordinates
 * - IFCTRIANGULATEDFACESET  → triangle indices + point list reference
 * - IFCCOLOURRGB            → color (r, g, b)
 * - IFCSURFACESTYLERENDERING → references colour
 * - IFCSURFACESTYLE          → references rendering
 * - IFCSTYLEDITEM            → links style to face set
 */

import fs from 'fs'
import readline from 'readline'
import { MeshStoreWriter, createTempPath } from './mesh-store'

export interface IfcReadResult {
  tempFile: string
  meshCount: number
  totalVertices: number
  totalFaces: number
  originalFileSize: number
}

// Parse a STEP entity line: #ID=IFCTYPE(params);
function parseEntityLine(line: string): { id: number; type: string; params: string } | null {
  // Find #ID=IFCTYPE(
  const eqIdx = line.indexOf('=')
  if (eqIdx === -1) return null
  const idStr = line.slice(1, eqIdx).trim()
  const id = parseInt(idStr)
  if (isNaN(id)) return null

  const parenOpen = line.indexOf('(', eqIdx)
  if (parenOpen === -1) return null
  const type = line.slice(eqIdx + 1, parenOpen).trim()

  // Find matching closing paren (last ');' on the line)
  const lastSemicolon = line.lastIndexOf(';')
  const lastParen = line.lastIndexOf(')', lastSemicolon)
  if (lastParen === -1) return null

  const params = line.slice(parenOpen + 1, lastParen)
  return { id, type, params }
}

// Parse a nested list of 3D coordinates from IFCCARTESIANPOINTLIST3D
// Format: ((x1,y1,z1),(x2,y2,z2),...),TagList
function parseCoordList(params: string): number[] {
  const vertices: number[] = []

  // Find the outer coordinate list
  let depth = 0
  let start = -1

  for (let i = 0; i < params.length; i++) {
    const ch = params.charCodeAt(i)
    if (ch === 40) { // '('
      depth++
      if (depth === 2) start = i + 1
    } else if (ch === 41) { // ')'
      depth--
      if (depth === 1 && start !== -1) {
        // End of one coordinate tuple - parse x,y,z
        const coord = params.slice(start, i)
        const c1 = coord.indexOf(',')
        const c2 = coord.indexOf(',', c1 + 1)
        if (c1 !== -1 && c2 !== -1) {
          vertices.push(
            parseFloat(coord.slice(0, c1)),
            parseFloat(coord.slice(c1 + 1, c2)),
            parseFloat(coord.slice(c2 + 1))
          )
        }
        start = -1
      } else if (depth === 0) {
        break
      }
    }
  }

  return vertices
}

// Parse triangle indices from IFCTRIANGULATEDFACESET
// Format: #pointListRef,Closed,Normals,((i1,i2,i3),(i4,i5,i6),...),PnIndex
function parseFaceSet(params: string): { pointListId: number; indices: number[] } | null {
  // First param is #ref to point list
  const hashIdx = params.indexOf('#')
  if (hashIdx === -1) return null
  let end = hashIdx + 1
  while (end < params.length && params.charCodeAt(end) >= 48 && params.charCodeAt(end) <= 57) end++
  const pointListId = parseInt(params.slice(hashIdx + 1, end))
  if (isNaN(pointListId)) return null

  // Skip to 4th parameter: count commas at depth 0
  let depth = 0
  let paramCount = 0

  for (let i = end; i < params.length; i++) {
    const ch = params.charCodeAt(i)
    if (ch === 40) depth++ // '('
    else if (ch === 41) depth-- // ')'
    else if (ch === 44 && depth === 0) { // ','
      paramCount++
      if (paramCount === 3) {
        // 4th parameter starts after this comma - parse the index list
        return { pointListId, indices: parseIndexList(params, i + 1) }
      }
    }
  }

  return null
}

// Parse nested index list ((i1,i2,i3),(i4,i5,i6),...)
function parseIndexList(params: string, startPos: number): number[] {
  const indices: number[] = []
  let depth = 0
  let start = -1

  for (let i = startPos; i < params.length; i++) {
    const ch = params.charCodeAt(i)
    if (ch === 40) { // '('
      depth++
      if (depth === 2) start = i + 1
    } else if (ch === 41) { // ')'
      depth--
      if (depth === 1 && start !== -1) {
        const tuple = params.slice(start, i)
        const c1 = tuple.indexOf(',')
        const c2 = tuple.indexOf(',', c1 + 1)
        if (c1 !== -1 && c2 !== -1) {
          // IFC indices are 1-based, convert to 0-based
          indices.push(
            parseInt(tuple.slice(0, c1)) - 1,
            parseInt(tuple.slice(c1 + 1, c2)) - 1,
            parseInt(tuple.slice(c2 + 1)) - 1
          )
        }
        start = -1
      } else if (depth === 0) {
        break
      }
    }
  }

  return indices
}

// Parse IFCCOLOURRGB($,R,G,B) or IFCCOLOURRGB('name',R,G,B)
function parseColourRGB(params: string): { r: number; g: number; b: number } | null {
  // Skip first param (name)
  let i = 0
  if (params.charCodeAt(i) === 39) { // single quote
    i = params.indexOf("'", i + 1) + 1
  } else {
    // Skip to first comma
    i = params.indexOf(',')
  }
  if (i === -1) return null
  // Skip comma
  while (i < params.length && params.charCodeAt(i) === 44) i++

  const rest = params.slice(i)
  const c1 = rest.indexOf(',')
  const c2 = rest.indexOf(',', c1 + 1)
  if (c1 === -1 || c2 === -1) return null

  return {
    r: parseFloat(rest.slice(0, c1)),
    g: parseFloat(rest.slice(c1 + 1, c2)),
    b: parseFloat(rest.slice(c2 + 1))
  }
}

// Parse IFCSTYLEDITEM(#itemRef,(#style1,...),$)
function parseStyledItem(params: string): { itemId: number; styleIds: number[] } | null {
  const hashIdx = params.indexOf('#')
  if (hashIdx === -1) return null
  let end = hashIdx + 1
  while (end < params.length && params.charCodeAt(end) >= 48 && params.charCodeAt(end) <= 57) end++
  const itemId = parseInt(params.slice(hashIdx + 1, end))
  if (isNaN(itemId)) return null

  const styleIds: number[] = []
  // Find refs inside the parenthesized list (second param)
  let inList = false
  for (let i = end; i < params.length; i++) {
    if (params.charCodeAt(i) === 40) { inList = true; continue } // '('
    if (params.charCodeAt(i) === 41 && inList) break // ')'
    if (inList && params.charCodeAt(i) === 35) { // '#'
      let j = i + 1
      while (j < params.length && params.charCodeAt(j) >= 48 && params.charCodeAt(j) <= 57) j++
      styleIds.push(parseInt(params.slice(i + 1, j)))
      i = j - 1
    }
  }

  return styleIds.length > 0 ? { itemId, styleIds } : null
}

// Extract all #ref IDs from params string
function extractRefs(params: string): number[] {
  const refs: number[] = []
  for (let i = 0; i < params.length; i++) {
    if (params.charCodeAt(i) === 35) { // '#'
      let j = i + 1
      while (j < params.length && params.charCodeAt(j) >= 48 && params.charCodeAt(j) <= 57) j++
      if (j > i + 1) refs.push(parseInt(params.slice(i + 1, j)))
      i = j - 1
    }
  }
  return refs
}

export async function readIfcFile(
  filePath: string,
  onProgress?: (message: string, percent: number) => void,
  excludedFaceSetIds?: Set<number>
): Promise<IfcReadResult> {
  const stats = fs.statSync(filePath)
  const fileSize = stats.size

  onProgress?.('Analisando arquivo IFC...', 2)

  // Data stores (small: just IDs and references)
  const colours = new Map<number, { r: number; g: number; b: number }>()
  const styleRenderings = new Map<number, number>()        // renderingId → colourId
  const styles = new Map<number, number[]>()                // styleId → [renderingId, ...]
  const faceSetToStyleIds = new Map<number, number[]>()     // faceSetId → styleIds (direct lookup)

  // Geometry data (large, cleared as consumed)
  const pointLists = new Map<number, number[]>()
  const faceSets = new Map<number, { pointListId: number; indices: number[] }>()

  // Mesh store writer
  const tempPath = createTempPath()
  const writer = new MeshStoreWriter(tempPath)
  let totalVertices = 0
  let totalFaces = 0
  let meshesWritten = 0

  // Resolve color for a face set using direct lookup (O(1) instead of O(n))
  const resolveColor = (faceSetId: number): { r: number; g: number; b: number } => {
    const styleIds = faceSetToStyleIds.get(faceSetId)
    if (styleIds) {
      for (const styleId of styleIds) {
        // styleId → IFCSURFACESTYLE → refs to renderings
        const renderingRefs = styles.get(styleId)
        if (renderingRefs) {
          for (const renderingId of renderingRefs) {
            const colourId = styleRenderings.get(renderingId)
            if (colourId !== undefined) {
              const colour = colours.get(colourId)
              if (colour) return colour
            }
          }
        }
        // Direct rendering ref
        const directColourId = styleRenderings.get(styleId)
        if (directColourId !== undefined) {
          const colour = colours.get(directColourId)
          if (colour) return colour
        }
      }
    }
    return { r: 0.7, g: 0.7, b: 0.7 }
  }

  // Track which pointLists are referenced by pending faceSets
  const pointListRefCount = new Map<number, number>()

  // Try to write a complete mesh and free its memory immediately
  const tryWriteMesh = (faceSetId: number): boolean => {
    const faceSet = faceSets.get(faceSetId)
    if (!faceSet) return false
    const vertices = pointLists.get(faceSet.pointListId)
    if (!vertices) return false

    const color = resolveColor(faceSetId)

    writer.writeMesh({
      name: `IFC_${faceSetId}`,
      vertices,
      indices: faceSet.indices,
      normals: [],
      color
    })

    totalVertices += Math.floor(vertices.length / 3)
    totalFaces += Math.floor(faceSet.indices.length / 3)
    meshesWritten++

    // Free memory immediately
    faceSets.delete(faceSetId)
    faceSetToStyleIds.delete(faceSetId)
    // Decrement point list ref count and delete if no longer needed
    const refCount = (pointListRefCount.get(faceSet.pointListId) || 1) - 1
    if (refCount <= 0) {
      pointLists.delete(faceSet.pointListId)
      pointListRefCount.delete(faceSet.pointListId)
    } else {
      pointListRefCount.set(faceSet.pointListId, refCount)
    }

    return true
  }

  // ---- Stream read the IFC file line by line ----
  const fileStream = fs.createReadStream(filePath, { encoding: 'utf-8' })
  const rl = readline.createInterface({ input: fileStream, crlfDelay: Infinity })

  let bytesRead = 0
  let lastProgressPercent = 0

  for await (const line of rl) {
    bytesRead += Buffer.byteLength(line, 'utf-8') + 2

    // Progress update
    const percent = 2 + Math.round((bytesRead / fileSize) * 90)
    if (percent > lastProgressPercent + 1) {
      lastProgressPercent = percent
      onProgress?.(
        `Lendo IFC: ${Math.round(bytesRead / 1048576)} MB / ${Math.round(fileSize / 1048576)} MB (${meshesWritten} meshes)`,
        Math.min(percent, 93)
      )
    }

    // Skip non-entity lines
    if (line.charCodeAt(0) !== 35) continue // '#'

    const entity = parseEntityLine(line)
    if (!entity) continue

    switch (entity.type) {
      case 'IFCCOLOURRGB': {
        const colour = parseColourRGB(entity.params)
        if (colour) colours.set(entity.id, colour)
        break
      }

      case 'IFCSURFACESTYLERENDERING': {
        const refs = extractRefs(entity.params)
        if (refs.length > 0) styleRenderings.set(entity.id, refs[0]) // first ref is colour
        break
      }

      case 'IFCSURFACESTYLE': {
        const refs = extractRefs(entity.params)
        if (refs.length > 0) styles.set(entity.id, refs)
        break
      }

      case 'IFCSTYLEDITEM': {
        const si = parseStyledItem(entity.params)
        if (si) {
          faceSetToStyleIds.set(si.itemId, si.styleIds)
          tryWriteMesh(si.itemId)
        }
        break
      }

      case 'IFCCARTESIANPOINTLIST3D': {
        const vertices = parseCoordList(entity.params)
        if (vertices.length > 0) {
          pointLists.set(entity.id, vertices)
        }
        break
      }

      case 'IFCTRIANGULATEDFACESET': {
        // Skip face sets belonging to excluded categories
        if (excludedFaceSetIds?.has(entity.id)) break

        const faceSet = parseFaceSet(entity.params)
        if (faceSet && faceSet.indices.length > 0) {
          faceSets.set(entity.id, faceSet)
          // Track how many faceSets reference this pointList
          pointListRefCount.set(faceSet.pointListId, (pointListRefCount.get(faceSet.pointListId) || 0) + 1)
          tryWriteMesh(entity.id)
        }
        break
      }
    }
  }

  // Process any remaining unmatched face sets
  for (const [faceSetId] of faceSets) {
    tryWriteMesh(faceSetId)
  }

  // Cleanup
  pointLists.clear()
  faceSets.clear()
  faceSetToStyleIds.clear()

  writer.close()

  onProgress?.(
    `Leitura completa: ${meshesWritten} meshes, ${totalVertices.toLocaleString()} vertices`,
    98
  )

  return {
    tempFile: tempPath,
    meshCount: meshesWritten,
    totalVertices,
    totalFaces,
    originalFileSize: fileSize
  }
}
